name: Package ComfyUI Blender Add-on

on:
  push:
    tags:
      - '*'

permissions:
  contents: write  # Required to upload to GitHub Releases

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies (if needed)
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y zip

      # Step 3: Extract tag name
      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Step 4: Package the comfyui_blender folder
      - name: Create zip package
        run: |
          zip -r comfyui_blender_$TAG_NAME.zip comfyui_blender

      
      # Step 5: Upload zip to GitHub Release
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: comfyui_blender_${{ env.TAG_NAME }}.zip
